name: code-verify

on:
  push:
    paths:
      - 'code/**'
      - '.github/workflows/code-verify.yml'
    branches:
      - develop
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - develop
      - main

jobs:
  verify:
    name: Build and analyze
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: code
    env:
      NODE_VERSION: '18.x'
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache-dependency-path: code/package-lock.json
          cache: 'npm'

      - name: Install dependencies
        working-directory: code
        run: npm ci
          
      - name: Run ESLint and generate report
        run: |
          npm run lint

      - name: Build app and rub tests
        working-directory: code
        run: |
          npm run build
          npm test -- --coverage
